[package]
name = "trigger-mcp"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
license = "Apache-2.0"
description = "A Spin trigger plugin for Model Context Protocol (MCP) servers"
repository = "https://github.com/yourusername/spin-trigger-mcp"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
clap = { version = "4.5", features = ["derive", "env"] }
futures = "0.3"
http = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spin-app = "3.0"
spin-core = "3.0"
spin-factor-variables = "3.0"
spin-factors = "3.0"
spin-runtime-factors = "3.0"
spin-telemetry = "3.0"
spin-trigger = "3.0"
tokio = { version = "1.40", features = ["macros", "rt", "net"] }
tracing = "0.1"
wasmtime = "27.0"
wasmtime-wasi = "27.0"

[[bin]]
name = "trigger-mcp"
path = "src/main.rs"

[workspace]