spin_manifest_version = 2

[application]
name = "mcp-weather-tool"
version = "0.1.0"
description = "Example MCP server providing weather information"
authors = ["Spin MCP Plugin Authors"]

[[trigger.mcp]]
component = "weather-service"
route = "/weather"

[component.weather-service]
source = "target/wasm32-wasip1/release/mcp_weather_tool.wasm"
# Allow the component to make outbound HTTP requests if needed
# allowed_outbound_hosts = ["https://api.weather.example.com"]

[component.weather-service.build]
command = "cargo build --target wasm32-wasip1 --release"