spin_manifest_version = 2

[application]
name = "demo-mcp"
version = "0.1.0"
authors = ["bowlofarugula <bowlofarugula@gmail.com>"]
description = "An MCP server component"

[variables]
# Add any configuration variables here
# api_key = { required = true, secret = true }

[[trigger.mcp]]
component = "demo-mcp"
route = "/mcp"

[component.demo-mcp]
source = "target/wasm32-wasip1/release/demo_mcp.wasm"
# Uncomment to allow outbound HTTP requests
# allowed_outbound_hosts = ["https://api.example.com"]

[component.demo-mcp.build]
command = "cargo build --target wasm32-wasip1 --release"