manifest_version = "1"
id = "toolkit-pointer"
description = "MCP server component with configurable workdir and source"
tags = ["rust", "mcp", "toolkit"]

[parameters]
project-description = { type = "string", prompt = "Description", default = "An MCP server component" }
route = { type = "string", prompt = "HTTP route path for the MCP server (default: /mcp)", default = "/mcp" }
workdir = { type = "string", prompt = "Relative path for the workdir (e.g., ./components/my-component)", default = "." }

[add_component]
skip_files = ["spin.toml"]
[add_component.snippets]
component = "component.txt"