spin_manifest_version = 2

[application]
name = "{{project-name}}"
version = "0.1.0"
description = "{{description}}"

[variables]
# Add any configuration variables here
# api_key = { required = true, secret = true }

[[trigger.mcp]]
component = "{{project-name | kebab_case}}"
route = "/{{name | kebab_case}}"

[component.{{project-name | kebab_case}}]
source = "target/wasm32-wasip1/release/{{project-name | snake_case}}.wasm"
# Uncomment to allow outbound HTTP requests
# allowed_outbound_hosts = ["https://api.example.com"]

[component.{{project-name | kebab_case}}.build]
command = "cargo build --target wasm32-wasip1 --release"